# Change these first
owner: nigr0mante # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Naupa House
    url: https://naupahouse.com
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/sony/336/bed_1f6cf-fe0f.png
  - name: Coffee Senses (testing)
    url: http://coffee.naupahouse.com
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/sony/336/hot-beverage_2615.png

assignees: # Users to assign downtime issues (optional)
  - nigr0mante

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://upptime.naupahouse.com
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  favicon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/sony/336/robot_1f916.png
  name: Upptime for Ivo services
  introTitle: "**Upptime** for Ivonne's services"
  introMessage: This tool is the open-source uptime monitor and status page, powered entirely by GitHub. More info at the bottom.
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub for Upptime project
      href: https://github.com/upptime/upptime
    - title: GitHub for my Upptime fork
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
